name: Lint

on:
  push:
    branches: master

jobs:
  lint:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Go Lint
        run: |
          go get -u golang.org/x/lint/golint
          go lint .
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python Lint
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          flake8 .
          black .
